jwt:
  secret: asdlkjDSljh2e1hjlDSA14dKQOCYEASLKJ11e2dwa7iAYSHe32dnwqs8dwqhlj21eASDSXXEEqewEEsad41214341
  lifetime: 10m
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: password
  jpa:
    ddl-auto: create-drop
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    use-legacy-processing: true
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  health:
    livenessstate:
      enabled: true
    redinessstate:
      enabled: true
    memory:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always