apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-manager
  template:
    metadata:
      labels:
        app: school-manager
    spec:
      containers:
        - name: school-manager
          image: yaroslav82/school-manager:1.0
          ports:
            - containerPort: 8080
          env:
            - name: "SPRING_DATASOURCE_URL"
              value: "jdbc:postgresql://postgres-service:5432/postgres"
