schoolManager:
  replicaCount: 1
  image:
    repository: yaroslav82/school-manager
    tag: "1.0"
    pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30007

labels:
  app: school-manager

postgres:
  database:
    name: "postgres"
    replicaCount: 1
    image:
      repository: postgres
      tag: latest
      containerPort: 5432
  service:
    name: "postgres-service"
    port: 5432
    targetPort: 5432
  postgresConfig:
    name: "postgres-config"
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
  labels:
    app: postgres

